# Generated by Django 5.0.4 on 2024-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='department_head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='security_head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
