# Generated by Django 5.0.4 on 2024-10-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0002_gatepass_department_head_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
